# Generated by Django 5.1.6 on 2025-02-26 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_categorie_produit_catégorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='catégorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magasin.categorie'),
        ),
    ]
