# Generated by Django 5.1.6 on 2025-02-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_fournisseur_produit_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
