# Generated by Django 5.1.6 on 2025-03-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_produitnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitnc',
            name='Duree_garantie',
            field=models.TextField(max_length=100),
        ),
    ]
