# Generated by Django 5.1.6 on 2025-04-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_commande'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
