# Generated by Django 5.1.6 on 2025-04-30 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_delete_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='catégorie',
            new_name='Categorie',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='type',
            new_name='typeProduit',
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.TextField(default='Tunis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produitnc',
            name='Duree_garantie',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCde', models.DateField(default=datetime.date.today, null=True)),
                ('totalCde', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Produit', models.ManyToManyField(to='magasin.produit')),
            ],
        ),
    ]
